# Codegen validation test: compiles the generated .hpp files and verifies layout.
# Requires running the Lua test first to generate headers.

add_executable(codegen_test test/codegen_test.cpp)
target_include_directories(codegen_test PRIVATE test)
target_compile_features(codegen_test PRIVATE cxx_std_20)
if(MSVC)
    target_compile_options(codegen_test PRIVATE /W4)
endif()

# All headers generated by the Lua test (single atomic invocation)
set(GENERATED_HEADERS
    ${CMAKE_CURRENT_SOURCE_DIR}/test/TemplateBox.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/test/TemplatePair.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/test/TemplateMixed.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/test/TemplateArray.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/test/TemplateList.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/test/TemplateUser.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/test/Foo.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/test/Bar.hpp
    ${CMAKE_CURRENT_SOURCE_DIR}/test/Baz.hpp
)

add_custom_command(
    OUTPUT ${GENERATED_HEADERS}
    COMMAND $<TARGET_FILE:repl> --test ${CMAKE_CURRENT_SOURCE_DIR}/test/test.lua
    DEPENDS repl ${CMAKE_CURRENT_SOURCE_DIR}/test/test.lua
    WORKING_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}
    COMMENT "Generating .hpp headers via Lua test"
)
add_custom_target(generate_headers DEPENDS ${GENERATED_HEADERS})
add_dependencies(codegen_test generate_headers)

add_test(NAME codegen_test COMMAND codegen_test)
